ALTER TABLE FOFRNECEDORES MODIFY COLUMN FOREC_NOME VARCHAR (100);

ALTER TABLE FORNECEDORES ADD COLUMN FORNEC_LOGRADOURO VARCHAR (100);

ALTER TABLE FORNECEDORES DROP COLUMN FORNEC_CONTATO TEXT NOT NULL;
ALTER TABLE FORNECEDORES ADD FORNEC_PESSOA_DE_CONTATO VARCHAR NOT NULL;

DROP TABLE FORNECEDORES;