CREATE SCHEMA SISTEMA_DE_GESTAO_EMPRESARIAL;
USE SISTEMA_DE_GESTÃO_EMPRESARIAL;

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT PRIMARY KEY,
CNPJ_CLIENTE VARCHAR (14) NOT NULL,
DATACADST_CLIENTE DATE NOT NULL,
RAMOATVDD_CLIENTE VARCHAR (100) NOT NULL,
RZSOCIAL_CLIENTE VARCHAR (100) NOT NULL,
ID_CLIENTE_END INT,
CONSTRAINT FK_ID_TIPO_DE_ENDERECO FOREIGN KEY (ID_TIPO_DE_ENDERECO)
REFERENCES TIPO_DE_ENDERECO (ID_TIPO_DE_ENDERECO)
);

CREATE TABLE IF NOT EXISTS TELEFONE_CLIENTES(
TELEFONES VARCHAR (11),
ID_CLIENTE INT,
CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
ID_EMPREGADO INT PRIMARY KEY,
NOME_EMPREGADO VARCHAR (45) NOT NULL,
DATAADM_EMPREGADO DATE NOT NULL,
ID_EMPREGADO_END INT,
CONSTRAINT FK_ID_EMPREGADO_END FOREIGN KEY (ID_EMPREGADO_END)
REFERENCES ENDERECOS (ID_EMPREGADO_END),
CONSTRAINT FK_ID_CARGO FOREIGN KEY (ID_CARGO)
REFERENCES CARGO (ID_CARGO)
);

CREATE TABLE IF NOT EXISTS TELEFONE_EMPREGADOS(
TELEFONES VARCHAR (11) NOT NULL,
ID_EMPREGADO INT,
CONSTRAINT FK_ID_EMPREGADO FOREIGN KEY (ID_EMPREGADO)
REFERENCES EMPREGADOS (ID_EMPREGADO)
);

CREATE TABLE IF NOT EXISTS CARGO(
ID_CARGO INT PRIMARY KEY,
NOME_CARGO VARCHAR (100) NOT NULL,
SALARIO_CARGO DECIMAL NOT NULL
); 

CREATE TABLE IF NOT EXISTS QUALIFICACOES(
QUALIFICACAO_EMPREGADO INT,
ID_EMPREGADO INT,
PRIMARY KEY (ID_EMPREGADO),
CONSTRAINT FK_ID_EMPREGADOQ FOREIGN KEY (ID_EMPREGADO)
REFERENCES EMPREGADOS (ID_EMPREGADO)
);

CREATE TABLE IF NOT EXISTS EMPRESAS(
CNPJ_EMPRESA INT PRIMARY KEY,
RZSOZIAL_EMPRESA VARCHAR (100) NOT NULL,
PCONTATO_EMPRESA TEXT NOT NULL,
ID_EMPRESA_END INT,
CONSTRAINT FK_ID_EMPRESA_END FOREIGN KEY (ID_EMPRESA_END)
REFERENCES ENDERECOS (ID_EMPRESA_END)
);

CREATE TABLE IF NOT EXISTS TELEFONE_EMPRESAS(
TELEFONE VARCHAR (11) NOT NULL,
CNPJ_EMPRESA INT,
CONSTRAINT FK_CNPJ_EMPRESA FOREIGN KEY (CNPJ_EMPRESA)
REFERENCES EMPRESAS (CNPJ_EMPRESA)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
CNPJ_FORNEC INT PRIMARY KEY,
RZSOZIAL_FORNEC VARCHAR (100) NOT NULL,
PCONTATO_FORNEC TEXT NOT NULL,
ID_FORNEC_END INT,
CONSTRAINT FK_ID_FORNEC_END FOREIGN KEY (ID_FORNEC_END)
REFERENCES ENDERECOS (ID_FORNEC_END)
);

CREATE TABLE IF NOT EXISTS TELEFONE_FORNECEDORES(
TELEFONE VARCHAR (11) NOT NULL,
CNPJ_FORNEC INT,
CONSTRAINT FK_CNPJ_FORNEC FOREIGN KEY (CNPJ_FORNEC)
REFERENCES FORNECEDORES (CNPJ_FORNEC)
);

CREATE TABLE IF NOT EXISTS TIPO_DE_ENDERECO(
ID_TIPO_DE_ENDERECO INT PRIMARY KEY,
NOME VARCHAR (100)
); 

CREATE TABLE IF NOT EXISTS ENDERECOS(
ID_ENDERECO INT PRIMARY KEY,
END_RUA VARCHAR(100) NOT NULL,	
END_NUMRUA INT,
END_LOGRADOURO VARCHAR (100) NOT NULL,
END_BAIRRO VARCHAR(100) NOT NULL,
END_CIDADE VARCHAR(100) NOT NULL,
END_ESTADO VARCHAR(100) NOT NULL,
END_CEP VARCHAR (20) NOT NULL,
END_PAIS VARCHAR(30) NOT NULL,
ID_TIPO_DE_ENDERECO INT,
ID_CLIENTE_END INT PRIMARY KEY,
ID_EMPREGADO_END INT PRIMARY KEY,
ID_EMPRESA_END INT PRIMARY KEY,
ID_FORNEC_END INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
ID_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR (45) NOT NULL,
COR_PROD VARCHAR (45) NOT NULL,
DIMENS_PROD VARCHAR (45) NOT NULL,
PESO_PROD DOUBLE NOT NULL,
PRECO_PROD DECIMAL NOT NULL,
TEMPFABRI_PROD TIME NOT NULL,
DESENHO_PROD VARCHAR (100) NOT NULL,
HRMAODEOBRA_PROD TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS(
ID_RE INT PRIMARY KEY,
QUANT_NECESS_RE DECIMAL NOT NULL,
UNIDADE_RE DECIMAL NOT NULL,
TEMPOUSO_RE TIME NOT NULL,
HR_MAO_DE_OBRA_RE TIME NOT NULL,
ID_PROD INT,
ID_EMPREGADO INT,
ID_MAQUINA INT,
ID_COMPONENTE INT,
CONSTRAINT FK_ID_PRODU FOREIGN KEY (ID_PROD)
REFERENCES PRODUTOS (ID_PROD),
CONSTRAINT FK_ID_EMPREGADORE FOREIGN KEY (ID_EMPREGADO)
REFERENCES EMPREGADOS (ID_EMPREGADO),
CONSTRAINT FK_ID_MAQUINARE FOREIGN KEY (ID_MAQUINA)
REFERENCES MAQUINAS (ID_MAQUINA),
CONSTRAINT FK_ID_COMPONENTERE FOREIGN KEY (ID_COMPONENTE)
REFERENCES COMPONENTES (ID_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS(
ID_ENCOM INT PRIMARY KEY,
DATINCLUS_ENCOM DATE NOT NULL,
VALORTOTAL_ENCOM DECIMAL NOT NULL,
VALORDESCO_ENCOM DECIMAL NOT NULL,
VALORLIQUI_ENCOM DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS FORMA_DE_PAGAMENTO(
ID_FORMA_PAGAMENTO INT PRIMARY KEY,
QUANTPARCELAS_PAGAMENTO INT NOT NULL,
ID_ENCOM INT,
ID_PROD INT ,
CONSTRAINT FK_ID_ENCOM FOREIGN KEY (ID_ENCOM)
REFERENCES ENCOMENDAS (ID_ENCOM),
CONSTRAINT FK_ID_PROD FOREIGN KEY (ID_PROD)
REFERENCES PRODUTOS (ID_PROD)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS_PRODUTOS(
ID_ENCOM INT,
ID_PROD INT,
primary key (id_encom,id_prod),
CONSTRAINT FK_ID_ENCOMEP FOREIGN KEY (ID_ENCOM)
REFERENCES ENCOMENDAS (ID_ENCOM),
CONSTRAINT FK_ID_PRODEP FOREIGN KEY (ID_PROD)
REFERENCES PRODUTOS (ID_PROD)
);

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTE(
ID_TIPO_COMPONENTE INT PRIMARY KEY,
NOME_TIPO_COMPONENTE VARCHAR (45) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPONENTES(
ID_COMPONENTE INT PRIMARY KEY,
NOME_COMPONENTE VARCHAR (45),
QUANTESTOQUE_COMPONENTE DECIMAL NOT NULL,
PRECOUNI_COMPONENTE DECIMAL NOT NULL,
UNIDADE_COMPONENTE VARCHAR (45),
ID_TIPO_COMPONENTE INT,
CONSTRAINT FK_ID_TIPO_COMPONENTE FOREIGN KEY (ID_TIPO_COMPONENTE)
REFERENCES TIPO_COMPONENTE (ID_TIPO_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES_COMPONENTES(
CNPJ_FORNEC INT,
ID_COMPONENTE INT,
primary key (cnpj_fornec,id_componente),
CONSTRAINT FK_CNPJ_FORNECE FOREIGN KEY (CNPJ_FORNEC)
REFERENCES FORNECEDORES (CNPJ_FORNEC),
CONSTRAINT FK_ID_COMPONENTES FOREIGN KEY (ID_COMPONENTE)
REFERENCES COMPONENTES (ID_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS REGISTRO_SUPRIMENTOS(
QUANTIDADE_RS DECIMAL NOT NULL,
DATANECESS_RS DATE NOT NULL,
ID_COMPONENTE INT,
ID_PROD INT,
CONSTRAINT FK_ID_COMPONENTE FOREIGN KEY (ID_COMPONENTE)
REFERENCES COMPONENTES (ID_COMPONENTE),
CONSTRAINT FK_ID_PRODRS FOREIGN KEY (ID_PROD)
REFERENCES PRODUTOS (ID_PROD)
);

CREATE TABLE IF NOT EXISTS MAQUINAS(
ID_MAQUINA INT PRIMARY KEY,
TEMPOVIDA_MAQUINA DATETIME NOT NULL,
DATACOMPRA_MAQUINA DATE NOT NULL,
DTFIMGARANTIA_MAQUINA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS REGISTRO_MANUTENCAO(
ID_RM INT PRIMARY KEY,
DATA_RM DATE NOT NULL,
DESCRICAO_RM TEXT NOT NULL,
ID_MAQUINA INT,
CONSTRAINT FK_ID_MAQUINA FOREIGN KEY (ID_MAQUINA)
REFERENCES MAQUINAS (ID_MAQUINA)
);

ALTER TABLE CLIENTES ADD COLUMN EMAIL_CLIENTE VARCHAR (100);

ALTER TABLE CLIENTES DROP COLUMN RAMOATVDD_CLIENTE;

ALTER TABLE CLIENTES MODIFY COLUMN RZSOCIAL_CLIENTE VARCHAR (200);

ALTER TABLE CLIENTES CHANGE COLMUN DATACADST_CLIENTE 
DATA_CADASTRAMENTO_CLIENTE DATE NOT NULL;


ALTER TABLE TELEFONE_CLIENTES 
ADD TELEFONE_FIXO_CLIENTE VARCHAR (9);

ALTER TABLE TELEFONE_CLIENTES 
DROP COLUMN TELEFONE_FIXO_CLIENTE VARCHAR(9);

ALTER TABLE TELEFONE_CLIENTES 
MODIFY COLUMN TELEFONES VARCHAR (14);

ALTER TABLE TELEFONE_CLIENTES
CHANGE COLUMN TELEFONES CELULAR VARCHAR (14);


ALTER TABLE EMPREGADOS 
ADD EMAIL_EMPREGADO VARCHAR (100);

ALTER TABLE EMPREGADOS 
DROP COLUMN DATAADM_EMPREGADO;

ALTER TABLE EMPREGADOS 
MODIFY COLUMN DATAADM_EMPREGADO DATETIME NOT NULL;

ALTER TABLE EMPREGADOS
CHANGE COLUMN NOME_EMPREGADO NOME_CP_EMPREGADO VARCHAR (100);


ALTER TABLE TELEFONE_EMPREGADOS
ADD TELEFONE_FIXO_EMPREGADO VARCHAR (9);

ALTER TABLE TELEFONE_EMPREGADOS 
DROP COLUMN TELEFONE_FIXO_EMPREGADO VARCHAR(9);

ALTER TABLE TELEFONE_EMPREGADOS 
MODIFY COLUMN TELEFONES VARCHAR (14);

ALTER TABLE TELEFONE_EMPREGADOS
CHANGE COLUMN TELEFONES CELULAR VARCHAR (14);


ALTER TABLE CARGO 
ADD CARGA_HORARIA_CARGO TIME NOT NULL;

ALTER TABLE CARGO 
DROP COLUMN SALARIO_CARGO;

ALTER TABLE CARGO 
MODIFY COLUMN NOME_CARGO VARCHAR (150);

ALTER TABLE CARGO 
CHANGE COLUMN NOME_CARGO CARGO_NOME VARCHAR (150);


ALTER TABLE QUALIFICACOES
ADD TEMPO_NA_AREA_EMPREGADO INT NOT NULL;

ALTER TABLE QUALIFICACOES
DROP COLUMN TEMPO_NA_AREA_EMPREGADO;

ALTER TABLE QUALIFICACOES
MODIFY COLUMN QUALIFICACAO_EMPREGADO TEXT NOT NULL;

ALTER TABLE QUALIFICACOES
CHANGE COLUMN QUALIFICACAO_EMPREGADO
QUALIFICACOES_EMPREGADO TEXT NOT NULL;


ALTER TABLE EMPRESAS 
ADD EMAIL_EMPRESA VARCHAR (100);

ALTER TABLE EMPRESAS 
DROP COLUMN RZSOZIAL_EMPRESA;

ALTER TABLE EMPRESAS 
MODIFY COLUMN EMAIL_EMPRESA VARCHAR (90) NOT NULL;

ALTER TABLE EMPRESAS 
CHANGE COLUMN RZSOZIAL_EMPRESA RAZAOSC_EMPRESA VARCHAR (90);


ALTER TABLE TELEFONE_EMPRESAS
ADD TELEFONE_FIXO_EMPRESA VARCHAR (9);

ALTER TABLE TELEFONE_EMPRESA 
DROP COLUMN TELEFONE_FIXO_EMPRESA VARCHAR(9);

ALTER TABLE TELEFONE_EMPRESA 
MODIFY COLUMN TELEFONES VARCHAR (14);

ALTER TABLE TELEFONE_EMPRESA
CHANGE COLUMN TELEFONES CELULAR VARCHAR (14);


ALTER TABLE FORNECEDORES 
ADD EMAIL_FORNEC VARCHAR (100) NOT NULL;

ALTER TABLE FORNECEDORES
DROP COLUMN PCONTATO_FORNEC;

ALTER TABLE FORNECEDORES 
MODIFY COLUMN EMAIL_FORNEC VARCHAR (90) NOT NULL;

ALTER TABLE FORNECEDORES
CHANGE COLUMN RZSOZIAL_FORNECE RAZAOSC_FORNECE VARCHAR (90);


ALTER TABLE TELEFONE_FORNECEDORES
ADD TELEFONE_FIXO_FORNECE VARCHAR (9);

ALTER TABLE TELEFONE_FORNECEDORES 
DROP COLUMN TELEFONE_FIXO_FORNECE VARCHAR(9);

ALTER TABLE TELEFONE_FORNECEDORES
MODIFY COLUMN TELEFONES VARCHAR (14);

ALTER TABLE TELEFONE_FORNECEDORES 
CHANGE COLUMN TELEFONES CELULAR VARCHAR (14);


ALTER TABLE TIPO_DE_ENDERECO
ADD COLUMN USO_PRINCIPAL VARCHAR(50);

ALTER TABLE TIPO_DE_ENDERECO
DROP COLUMN NOME;

ALTER TABLE TIPO_DE_ENDERECO
MODIFY COLUMN NOME VARCHAR(200);

ALTER TABLE TIPO_DE_ENDERECO
CHANGE COLUMN NOME DESCRICAO VARCHAR(100);


ALTER TABLE ENDERECOS
ADD COLUMN END_OBSERVACOES TEXT;

ALTER TABLE ENDERECOS
DROP COLUMN END_NUMRUA;

ALTER TABLE ENDERECOS
MODIFY COLUMN END_CEP CHAR(8) NOT NULL;

ALTER TABLE ENDERECOS
CHANGE COLUMN END_LOGRADOURO 
END_TIPO_LOGRADOURO VARCHAR(100) NOT NULL;


ALTER TABLE PRODUTOS
ADD COLUMN CATEGORIA_PROD VARCHAR(50);

ALTER TABLE PRODUTOS
DROP COLUMN COR_PROD;

ALTER TABLE PRODUTOS
MODIFY COLUMN PESO_PROD DECIMAL(10,2);

ALTER TABLE PRODUTOS
CHANGE COLUMN TEMPFABRI_PROD TEMPO_FABRICACAO TIME NOT NULL;


ALTER TABLE RECURSOS_ESPECIFICOS
ADD COLUMN CUSTO_RE DECIMAL(10,2);

ALTER TABLE RECURSOS_ESPECIFICOS
DROP COLUMN UNIDADE_RE;

ALTER TABLE RECURSOS_ESPECIFICOS
MODIFY COLUMN QUANT_NECESS_RE INT;

ALTER TABLE RECURSOS_ESPECIFICOS
CHANGE COLUMN HR_MAO_DE_OBRA_RE 
TEMPO_MAO_DE_OBRA TIME NOT NULL;


ALTER TABLE ENCOMENDAS
ADD COLUMN ID_CLIENTE INT;

ALTER TABLE ENCOMENDAS
DROP COLUMN VALORDESCO_ENCOM;

ALTER TABLE ENCOMENDAS
MODIFY COLUMN VALORTOTAL_ENCOM DECIMAL(10,2) NOT NULL,
MODIFY COLUMN VALORLIQUI_ENCOM DECIMAL(10,2) NOT NULL;

ALTER TABLE ENCOMENDAS
CHANGE COLUMN DATINCLUS_ENCOM DATA_INCLUSAO DATE NOT NULL;


ALTER TABLE FORMA_DE_PAGAMENTO
ADD COLUMN TIPO_PAGAMENTO VARCHAR(50);

ALTER TABLE FORMA_DE_PAGAMENTO
DROP COLUMN QUANTPARCELAS_PAGAMENTO;

ALTER TABLE FORMA_DE_PAGAMENTO
MODIFY COLUMN ID_ENCOM INT NOT NULL,
MODIFY COLUMN ID_PROD INT NOT NULL;

ALTER TABLE FORMA_DE_PAGAMENTO
CHANGE COLUMN ID_FORMA_PAGAMENTO 
CODIGO_PAGAMENTO INT PRIMARY KEY;


ALTER TABLE ENCOMENDAS_PRODUTOS
ADD COLUMN QUANTIDADE INT;

ALTER TABLE ENCOMENDAS_PRODUTOS
DROP PRIMARY KEY,
DROP COLUMN ID_ENCOM;


ALTER TABLE TIPO_COMPONENTE
ADD COLUMN MATERIAL VARCHAR(50);

ALTER TABLE TIPO_COMPONENTE
DROP COLUMN NOME_TIPO_COMPONENTE;

ALTER TABLE TIPO_COMPONENTE
MODIFY COLUMN NOME_TIPO_COMPONENTE VARCHAR(100) NOT NULL;

ALTER TABLE TIPO_COMPONENTE
CHANGE COLUMN NOME_TIPO_COMPONENTE 
DESCRICAO VARCHAR(45) NOT NULL;


ALTER TABLE COMPONENTES
ADD COLUMN DATA_ULT_ATUALIZACAO DATE;

ALTER TABLE COMPONENTES
DROP COLUMN UNIDADE_COMPONENTE;

ALTER TABLE COMPONENTES
MODIFY COLUMN NOME_COMPONENTE VARCHAR(100);

ALTER TABLE COMPONENTES
CHANGE COLUMN QUANTESTOQUE_COMPONENTE 
QUANTIDADE_ESTOQUE DECIMAL NOT NULL;


ALTER TABLE FORNECEDORES_COMPONENTES
ADD COLUMN PRECO_COMPRA DECIMAL(10,2);

ALTER TABLE FORNECEDORES_COMPONENTES
MODIFY COLUMN CNPJ_FORNEC VARCHAR(20);

ALTER TABLE FORNECEDORES_COMPONENTES
CHANGE COLUMN CNPJ_FORNEC CNPJ_FORNECEDOR INT;

ALTER TABLE FORNECEDORES_COMPONENTES
DROP PRIMARY KEY;


ALTER TABLE MAQUINAS
ADD COLUMN NUMERO_SERIE VARCHAR(50);

ALTER TABLE MAQUINAS
DROP COLUMN TEMPOVIDA_MAQUINA;

ALTER TABLE MAQUINAS
MODIFY COLUMN DATACOMPRA_MAQUINA DATE NOT NULL,
MODIFY COLUMN DTFIMGARANTIA_MAQUINA DATE NOT NULL;

ALTER TABLE MAQUINAS
CHANGE COLUMN TEMPOVIDA_MAQUINA 
TEMPO_VIDA_ESTIMADO DATETIME NOT NULL;


ALTER TABLE REGISTRO_MANUTENCAO
ADD COLUMN CUSTO_MANUTENCAO DECIMAL(10,2);

ALTER TABLE REGISTRO_MANUTENCAO
DROP COLUMN DESCRICAO_RM;

ALTER TABLE REGISTRO_MANUTENCAO
MODIFY COLUMN DATA_RM DATETIME NOT NULL;

ALTER TABLE REGISTRO_MANUTENCAO
CHANGE COLUMN ID_RM CODIGO_MANUTENCAO INT PRIMARY KEY;