CREATE SCHEMA ACADEMIA_SAUDE_EM_MOVIMENTO;
USE ACADEMIA_SAUDE_EM_MOVIMENTO;

CREATE TABLE IF NOT EXISTS ALUNOS(
ID_ALUNO INT PRIMARY KEY,
ALUNO_NOME VARCHAR (100) NOT NULL,
ALUNO_CPF VARCHAR (11) NOT NULL,
ALUNO_DATA_NASC DATE NOT NULL,
ALUNO_RUA VARCHAR (100) NOT NULL,
ALUNO_NUMRUA INT,
ALUNO_BAIRRO VARCHAR(100) NOT NULL,
ALUNO_CIDADE VARCHAR(100) NOT NULL,
ALUNO_ESTADO VARCHAR(100) NOT NULL,
ALUNO_CEP VARCHAR (14) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODALIDADES(
ID_MODALIDADE INT PRIMARY KEY,
MODALIDADE_NOME VARCHAR (100) NOT NULL,
MODALIDADE_DESCRICAO TEXT
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
ID_INSTRUTOR INT PRIMARY KEY,
INSTRUTOR_NOME VARCHAR (100) NOT NULL,
INSTRUTOR_ESPEC VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PLANO_DE_TREINAMENTO(
ID_PT INT PRIMARY KEY,
PT_DATA_INICIO DATE NOT NULL,
PT_OBJETIVO TEXT NOT NULL,
ID_ALUNO INT NOT NULL,
ID_INSTRUTOR INT NOT NULL,
CONSTRAINT FK_ID_ALUNOPT FOREIGN KEY (ID_ALUNO)
REFERENCES ALUNOS (ID_ALUNO),
CONSTRAINT FK_ID_INSTRUTORPT FOREIGN KEY (ID_INSTRUTOR)
REFERENCES INSTRUTORES (ID_INSTRUTOR)
);

CREATE TABLE IF NOT EXISTS AULAS(
  ID_AULA INT PRIMARY KEY,
  AULA_DATA_HORA DATETIME NOT NULL,
  AULA_CAPACIDADE INT NOT NULL,
  ID_ALUNO INT NOT NULL,
  ID_MODALIDADE INT NOT NULL,
  ID_INSTRUTOR INT NOT NULL,
  CONSTRAINT FK_ID_ALUNOA FOREIGN KEY (ID_ALUNO)
  REFERENCES ALUNOS (ID_ALUNO),
  CONSTRAINT FK_ID_MODALIDADEA FOREIGN KEY (ID_MODALIDADE) 
  REFERENCES MODALIDADES (ID_MODALIDADE),
  CONSTRAINT FK_ID_INSTRUTORA FOREIGN KEY (ID_INSTRUTOR)
  REFERENCES INSTRUTORES (ID_INSTRUTOR)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
  ID_PAGA INT PRIMARY KEY,
  PAGA_VALOR DECIMAL (10,2) NOT NULL,
  PAGA_DATA DATE NOT NULL,
  STATUS ENUM('PAGO','PENDENTE'),
  ID_ALUNO INT NOT NULL,
  CONSTRAINT FK_ID_ALUNOPAGA FOREIGN KEY (ID_ALUNO) 
  REFERENCES ALUNOS (ID_ALUNO)
);

ALTER TABLE ALUNOS ADD EMAIL VARCHAR (100);

ALTER TABLE ALUNOS DROP COLUMN ALUNO_NUMRUA INT;

ALTER TABLE ALUNOS MODIFY COLUMN ALUNO_CEP VARCHAR (9);

ALTER TABLE ALUNOS CHANGE COLUMN ALUNO_NOME ALUNO_NOMECOMPLETO VARCHAR (100;


ALTER TABLE MODALIDADES
ADD COLUMN MODALIDADE_NIVEL ENUM('INICIANTE','INTERMEDIARIO','AVANCADO');

ALTER TABLE MODALIDADES DROP COLUMN MODALIDADE_DESCRICAO;

ALTER TABLE MODALIDADES MODIFY COLUMN MODALIDADE_NOME VARCHAR (200) NOT NULL;

ALTER TABLE MODALIDADES 
CHANGE COLUMN MODALIDADE_NOME NOME_MODALIDADE VARCHAR (200) NOT NULL;


ALTER TABLE INSTRUTORES ADD INSTRUTOR_TELEFONE VARCHAR(20);

ALTER TABLE INSTRUTORES DROP COLUMN INSTRUTOR_ESPEC;

ALTER TABLE INSTRUTORES
MODIFY COLUMN INSTRUTOR_NOME VARCHAR(150) NOT NULL;

ALTER TABLE INSTRUTORES
CHANGE COLUMN INSTRUTOR_NOME NOME_INSTRUTOR VARCHAR(150) NOT NULL;


ALTER TABLE PLANO_DE_TREINAMENTO ADD COLUMN PT_DURACAO INT;

ALTER TABLE PLANO_DE_TREINAMENTO DROP COLUMN PT_OBJETIVO;

ALTER TABLE PLANO_DE_TREINAMENTO
MODIFY COLUMN PT_DATA_INICIO DATE DEFAULT CURRENT_DATE;

ALTER TABLE PLANO_DE_TREINAMENTO
CHANGE COLUMN PT_DATA_INICIO PT_DATA_INICIO_TREINO DATE NOT NULL;


ALTER TABLE AULAS ADD COLUMN AULA_OBSERVACOES TEXT;

ALTER TABLE AULAS DROP COLUMN AULA_CAPACIDADE;

ALTER TABLE AULAS 
CHANGE COLUMN AULA_DATA_HORA AULA_HORARIO DATETIME NOT NULL;

ALTER TABLE AULAS MODIFY COLUMN AULA_DATA_HORA TIME NOT NULL;


ALTER TABLE PAGAMENTOS
ADD COLUMN PAGA_FORMA_PAGTO ENUM('DINHEIRO', 'CARTAO', 'CHEQUE');

ALTER TABLE PAGAMENTOS DROP COLUMN PAGA_DATA;

ALTER TABLE PAGAMENTOS
MODIFY COLUMN PAGA_VALOR DECIMAL(12,2) NOT NULL;

ALTER TABLE PAGAMENTOS
CHANGE COLUMN PAGA_VALOR VALOR_PAGA DECIMAL(12,2) NOT NULL;


DROP TABLE ACADEMIA_SAUDE_EM_MOVIMENTO;