CREATE SCHEMA SISTEMA_DE_GESTÃO_EMPRESARIAL;
USE SISTEMA_DE_GESTÃO_EMPRESARIAL;

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT PRIMARY KEY,
CNPJ_CLIENTE VARCHAR (14) NOT NULL,
DATACADST_CLIENTE DATE NOT NULL,
RAMOATVDD_CLIENTE VARCHAR (100) NOT NULL,
RZSOCIAL_CLIENTE VARCHAR (100) NOT NULL,
ID_CLIENTE_END INT,
CONSTRAINT FK_ID_TIPO_DE_ENDERECO FOREIGN KEY (ID_TIPO_DE_ENDERECO)
REFERENCES TIPO_DE_ENDERECO (ID_TIPO_DE_ENDERECO)
);

CREATE TABLE IF NOT EXISTS TELEFONE_CLIENTES(
TELEFONES VARCHAR (11),
ID_CLIENTE INT,
CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
ID_EMPREGADO INT PRIMARY KEY,
NOME_EMPREGADO VARCHAR (45) NOT NULL,
DATAADM_EMPREGADO DATE NOT NULL,
ID_EMPREGADO_END INT,
CONSTRAINT FK_ID_EMPREGADO_END FOREIGN KEY (ID_EMPREGADO_END)
REFERENCES ENDERECOS (ID_EMPREGADO_END),
CONSTRAINT FK_ID_CARGO FOREIGN KEY (ID_CARGO)
REFERENCES CARGO (ID_CARGO)
);

CREATE TABLE IF NOT EXISTS TELEFONE_EMPREGADOS(
TELEFONES VARCHAR (11) NOT NULL,
ID_EMPREGADO INT,
CONSTRAINT FK_ID_EMPREGADO FOREIGN KEY (ID_EMPREGADO)
REFERENCES EMPREGADOS (ID_EMPREGADO)
);

CREATE TABLE IF NOT EXISTS CARGO(
ID_CARGO INT PRIMARY KEY,
NOME_CARGO VARCHAR (100) NOT NULL,
SALARIO_CARGO DECIMAL NOT NULL
); 

CREATE TABLE IF NOT EXISTS QUALIFICACOES(
QUALIFICACAO_EMPREGADO INT,
ID_EMPREGADO INT,
PRIMARY KEY (ID_EMPREGADO),
CONSTRAINT FK_ID_EMPREGADOQ FOREIGN KEY (ID_EMPREGADO)
REFERENCES EMPREGADOS (ID_EMPREGADO)
);

CREATE TABLE IF NOT EXISTS EMPRESAS(
CNPJ_EMPRESA INT PRIMARY KEY,
RZSOZIAL_EMPRESA VARCHAR (100) NOT NULL,
PCONTATO_EMPRESA TEXT NOT NULL,
ID_EMPRESA_END INT,
CONSTRAINT FK_ID_EMPRESA_END FOREIGN KEY (ID_EMPRESA_END)
REFERENCES ENDERECOS (ID_EMPRESA_END)
);

CREATE TABLE IF NOT EXISTS TELEFONE_EMPRESAS(
TELEFONE VARCHAR (11) NOT NULL,
CNPJ_EMPRESA INT,
CONSTRAINT FK_CNPJ_EMPRESA FOREIGN KEY (CNPJ_EMPRESA)
REFERENCES EMPRESAS (CNPJ_EMPRESA)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
CNPJ_FORNEC INT PRIMARY KEY,
RZSOZIAL_FORNEC VARCHAR (100) NOT NULL,
PCONTATO_FORNEC TEXT NOT NULL,
ID_FORNEC_END INT,
CONSTRAINT FK_ID_FORNEC_END FOREIGN KEY (ID_FORNEC_END)
REFERENCES ENDERECOS (ID_FORNEC_END)
);

CREATE TABLE IF NOT EXISTS TELEFONE_FORNECEDORES(
TELEFONE VARCHAR (11) NOT NULL,
CNPJ_FORNEC INT,
CONSTRAINT FK_CNPJ_FORNEC FOREIGN KEY (CNPJ_FORNEC)
REFERENCES FORNECEDORES (CNPJ_FORNEC)
);

CREATE TABLE IF NOT EXISTS TIPO_DE_ENDERECO(
ID_TIPO_DE_ENDERECO INT PRIMARY KEY,
NOME VARCHAR (100)
); 

CREATE TABLE IF NOT EXISTS ENDERECOS(
ID_ENDERECO INT PRIMARY KEY,
END_RUA VARCHAR(100) NOT NULL,	
END_NUMRUA INT,
END_LOGRADOURO VARCHAR (100) NOT NULL,
END_BAIRRO VARCHAR(100) NOT NULL,
END_CIDADE VARCHAR(100) NOT NULL,
END_ESTADO VARCHAR(100) NOT NULL,
END_CEP VARCHAR (20) NOT NULL,
END_PAIS VARCHAR(30) NOT NULL,
ID_TIPO_DE_ENDERECO INT,
ID_CLIENTE_END INT PRIMARY KEY,
ID_EMPREGADO_END INT PRIMARY KEY,
ID_EMPRESA_END INT PRIMARY KEY,
ID_FORNEC_END INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
ID_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR (45) NOT NULL,
COR_PROD VARCHAR (45) NOT NULL,
DIMENS_PROD VARCHAR (45) NOT NULL,
PESO_PROD DOUBLE NOT NULL,
PRECO_PROD DECIMAL NOT NULL,
TEMPFABRI_PROD TIME NOT NULL,
DESENHO_PROD VARCHAR (100) NOT NULL,
HRMAODEOBRA_PROD TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS(
ID_RE INT PRIMARY KEY,
QUANT_NECESS_RE DECIMAL NOT NULL,
UNIDADE_RE DECIMAL NOT NULL,
TEMPOUSO_RE TIME NOT NULL,
HR_MAO_DE_OBRA_RE TIME NOT NULL,
ID_PROD INT,
ID_EMPREGADO INT,
ID_MAQUINA INT,
ID_COMPONENTE INT,
CONSTRAINT FK_ID_PRODU FOREIGN KEY (ID_PROD)
REFERENCES PRODUTOS (ID_PROD),
CONSTRAINT FK_ID_EMPREGADORE FOREIGN KEY (ID_EMPREGADO)
REFERENCES EMPREGADOS (ID_EMPREGADO),
CONSTRAINT FK_ID_MAQUINARE FOREIGN KEY (ID_MAQUINA)
REFERENCES MAQUINAS (ID_MAQUINA),
CONSTRAINT FK_ID_COMPONENTERE FOREIGN KEY (ID_COMPONENTE)
REFERENCES COMPONENTES (ID_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS(
ID_ENCOM INT PRIMARY KEY,
DATINCLUS_ENCOM DATE NOT NULL,
VALORTOTAL_ENCOM DECIMAL NOT NULL,
VALORDESCO_ENCOM DECIMAL NOT NULL,
VALORLIQUI_ENCOM DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS FORMA_DE_PAGAMENTO(
ID_FORMA_PAGAMENTO INT PRIMARY KEY,
QUANTPARCELAS_PAGAMENTO INT NOT NULL,
ID_ENCOM INT,
ID_PROD INT ,
CONSTRAINT FK_ID_ENCOM FOREIGN KEY (ID_ENCOM)
REFERENCES ENCOMENDAS (ID_ENCOM),
CONSTRAINT FK_ID_PROD FOREIGN KEY (ID_PROD)
REFERENCES PRODUTOS (ID_PROD)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS_PRODUTOS(
ID_ENCOM INT,
ID_PROD INT,
primary key (id_encom,id_prod),
CONSTRAINT FK_ID_ENCOMEP FOREIGN KEY (ID_ENCOM)
REFERENCES ENCOMENDAS (ID_ENCOM),
CONSTRAINT FK_ID_PRODEP FOREIGN KEY (ID_PROD)
REFERENCES PRODUTOS (ID_PROD)
);

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTE(
ID_TIPO_COMPONENTE INT PRIMARY KEY,
NOME_TIPO_COMPONENTE VARCHAR (45) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPONENTES(
ID_COMPONENTE INT PRIMARY KEY,
NOME_COMPONENTE VARCHAR (45),
QUANTESTOQUE_COMPONENTE DECIMAL NOT NULL,
PRECOUNI_COMPONENTE DECIMAL NOT NULL,
UNIDADE_COMPONENTE VARCHAR (45),
ID_TIPO_COMPONENTE INT,
CONSTRAINT FK_ID_TIPO_COMPONENTE FOREIGN KEY (ID_TIPO_COMPONENTE)
REFERENCES TIPO_COMPONENTE (ID_TIPO_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES_COMPONENTES(
CNPJ_FORNEC INT,
ID_COMPONENTE INT,
primary key (cnpj_fornec,id_componente),
CONSTRAINT FK_CNPJ_FORNECE FOREIGN KEY (CNPJ_FORNEC)
REFERENCES FORNECEDORES (CNPJ_FORNEC),
CONSTRAINT FK_ID_COMPONENTES FOREIGN KEY (ID_COMPONENTE)
REFERENCES COMPONENTES (ID_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS REGISTRO_SUPRIMENTOS(
QUANTIDADE_RS DECIMAL NOT NULL,
DATANECESS_RS DATE NOT NULL,
ID_COMPONENTE INT,
ID_PROD INT,
CONSTRAINT FK_ID_COMPONENTE FOREIGN KEY (ID_COMPONENTE)
REFERENCES COMPONENTES (ID_COMPONENTE),
CONSTRAINT FK_ID_PRODRS FOREIGN KEY (ID_PROD)
REFERENCES PRODUTOS (ID_PROD)
);

CREATE TABLE IF NOT EXISTS MAQUINAS(
ID_MAQUINA INT PRIMARY KEY,
TEMPOVIDA_MAQUINA DATETIME NOT NULL,
DATACOMPRA_MAQUINA DATE NOT NULL,
DTFIMGARANTIA_MAQUINA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS REGISTRO_MANUTENCAO(
ID_RM INT PRIMARY KEY,
DATA_RM DATE NOT NULL,
DESCRICAO_RM TEXT NOT NULL,
ID_MAQUINA INT,
CONSTRAINT FK_ID_MAQUINA FOREIGN KEY (ID_MAQUINA)
REFERENCES MAQUINAS (ID_MAQUINA)
);