CREATE SCHEMA SISTEMA_DE_GESTÃO_EMPRESARIAL;
USE SISTEMA_DE_GESTÃO_EMPRESARIAL;

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT,
CNPJ_CLIENTE VARCHAR (14),
PRIMARY KEY (ID_CLIENTE,CNPJ_CLIENTE),
DATACADST_CLIENTE DATE NOT NULL,
RAMOATVDD_CLIENTE VARCHAR (100),
RZSOCIAL_CLIENTE VARCHAR (100)
);

CREATE TABLE IF NOT EXISTS TELEFONE_CLIENTES(
TELEFONES VARCHAR (11),
ID_CLIENTE INT NOT NULL,
CNPJ_CLIENTE VARCHAR (14),
CONSTRAINT FK_ID_CLIENTE_CNPJ_CLIENTE FOREIGN KEY (ID_CLIENTE,CNPJ_CLIENTE)
REFERENCES CLIENTES (ID_CLIENTE,CNPJ_CLIENTE)
);

CREATE TABLE IF NOT EXISTS ENDERECO_CLIENTES(
RUA VARCHAR(100) NOT NULL,
NUMRUA INT,
LOGRADOURO VARCHAR (100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
ESTADO VARCHAR(100) NOT NULL,
CEP VARCHAR (20) NOT NULL,
PAIS VARCHAR(30) NOT NULL,
ID_TIPO_DE_ENDERECO INT NOT NULL,
CONSTRAINT FK_ID_TIPO_DE_ENDERECO FOREIGN KEY (ID_TIPO_DE_ENDERECO)
REFERENCES TIPO_DE_ENDERECO (ID_TIPO_DE_ENDERECO),
ID_CLIENTE INT NOT NULL,
CNPJ_CLIENTE VARCHAR (14),
CONSTRAINT FK_ID_CLIENTE_CNPJ_CLIENTE FOREIGN KEY (ID_CLIENTE,CNPJ_CLIENTE)
REFERENCES CLIENTES (ID_CLIENTE,CNPJ_CLIENTE)
);

CREATE TABLE IF NOT EXISTS TIPO_DE_ENDERECO(
ID_TIPO_DE_ENDERECO INT PRIMARY KEY,
NOME VARCHAR (100)
); 

CREATE TABLE IF NOT EXISTS ENDERECOS(
RUA VARCHAR(100) NOT NULL,
NUMRUA INT,
LOGRADOURO VARCHAR (100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
ESTADO VARCHAR(100) NOT NULL,
CEP VARCHAR (20) NOT NULL,
PAIS VARCHAR(30) NOT NULL,
ID_TIPO_DE_ENDERECO INT NOT NULL,
CONSTRAINT FK_ID_TIPO_DE_ENDERECO FOREIGN KEY (ID_TIPO_DE_ENDERECO)
REFERENCES TIPO_DE_ENDERECO (ID_TIPO_DE_ENDERECO)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
ID_EMPREGADO INT PRIMARY KEY,
NOME_EMPREGADO VARCHAR (45) NOT NULL,
CARGO_EMPREGADO VARCHAR (45) NOT NULL,
SALARIO_EMPREGADO DECIMAL NOT NULL,
DATAADM_EMPREGADO DATE NOT NULL,
QUALIFI_EMPREGADO VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TELEFONE_EMPREGADOS(
TELEFONES VARCHAR (11) NOT NULL,
ID_EMPREGADO INT NOT NULL,
CONSTRAINT FK_ID_EMPREGADO FOREIGN KEY (ID_EMPREGADO)
REFERENCES EMPREGADOS (ID_EMPREGADO)
);

CREATE TABLE IF NOT EXISTS ENDERECO_EMPREGADOS(
RUA VARCHAR(100) NOT NULL,
NUMRUA INT,
LOGRADOURO VARCHAR (100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
ESTADO VARCHAR(100) NOT NULL,
CEP VARCHAR (20) NOT NULL,
PAIS VARCHAR(30) NOT NULL,
ID_EMPREGADO INT NOT NULL,
CONSTRAINT FK_ID_EMPREGADO FOREIGN KEY (ID_EMPREGADO)
REFERENCES EMPREGADOS (ID_EMPREGADO)
);