CREATE DATABASE IF NOT EXISTS EMPRESA_PASSAGENS_AEREAS;
USE EMPRESA_PASSAGENS_AEREAS;

CREATE TABLE IF NOT EXISTS PASSAGEIROS (
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(30) NOT NULL,
PASS_TELEFONE VARCHAR(15) NOT NULL,
PASS_RUA VARCHAR(45) NOT NULL,
PASS_NUMRUA INT NOT NULL,
PASS_BAIRRO VARCHAR(45) NOT NULL,
PASS_CIDADE VARCHAR(45) NOT NULL,
PASS_ESTADO VARCHAR(45) NOT NULL,
PASS_CEP VARCHAR (20) NOT NULL,
PASS_PAIS VARCHAR(30) NOT NULL,
PASS_EMAIL VARCHAR (30) NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR (30) NOT NULL,
AEROP_RUA VARCHAR(45) NOT NULL,
AEROP_NUMRUA INT NOT NULL,
AEROP_BAIRRO VARCHAR(45) NOT NULL,
AEROP_CIDADE VARCHAR(45) NOT NULL,
AEROP_ESTADO VARCHAR(45) NOT NULL,
AEROP_CEP VARCHAR (20) NOT NULL,
AEROP_PAIS VARCHAR(30) NOT NULL,
AEROP_LATITUDE FLOAT NOT NULL,
AEROP_LONGITUDE FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFIXO INT PRIMARY KEY,
AERON_MODELO VARCHAR (30) NOT NULL,
AERON_ANOFABR INT NOT NULL,
AERON_AUTONOMIA VARCHAR (45) NOT NULL,
AERON_CAPACIDADE INT NOT NULL,
AERON_FABRICANTE VARCHAR (45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNCK_NOME VARCHAR (45) NOT NULL,
FUNCK_CPF VARCHAR (14) NOT NULL,
FUNCK_DATANASC DATE NOT NULL,
FUNCK_RUA VARCHAR(45) NOT NULL,
FUNCK_NUMRUA INT NOT NULL,
FUNCK_BAIRRO VARCHAR(45) NOT NULL,
FUNCK_CIDADE VARCHAR(45) NOT NULL,
FUNCK_ESTADO VARCHAR(45) NOT NULL,
FUNCK_CEP VARCHAR (20) NOT NULL,
FUNCK_PAIS VARCHAR(30) NOT NULL,
FUNCK_FUNCAO VARCHAR (45) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM VARCHAR (45) NOT NULL,
VOO_AEROP_DESTINO VARCHAR (45) NOT NULL,
AERON_PREFIXO INT NOT NULL,
AEROP_COD INT NOT NULL,
CONSTRAINT FK_AERON_PREFIXO FOREIGN KEY (AERON_PREFIXO)
REFERENCES AERONAVES (AERON_PREFIXO),
CONSTRAINT FK_AEROP_COD FOREIGN KEY(AEROP_COD)
REFERENCES AEROPORTOS (AEROP_COD)
);

CREATE TABLE IF NOT EXISTS RESERVAS(
RESERVA_COD INT PRIMARY KEY,
PASS_CPF INT NOT NULL,
VOO_ID INT NOT NULL,
RESERVA_DATA DATE NOT NULL,
CONSTRAINT FK_PASS_CPF FOREIGN KEY (PASS_CPF)
REFERENCES PASSAGEIROS (PASS_CPF),
CONSTRAINT FK_VOO_ID FOREIGN KEY (VOO_ID) 
REFERENCES VOOS (VOO_ID)
);

CREATE TABLE IF NOT EXISTS EQUIPES(
EQUIPES_FUNC_ID INT,
EQUIPES_VOO_ID INT,
PRIMARY KEY (EQUIPES_FUNC_ID,EQUIPES_VOO_ID),
CONSTRAINT FK_EQUIPES_FUNC_ID FOREIGN KEY (EQUIPES_FUNC_ID) REFERENCES FUNCIONARIOS (FUNC_ID),
CONSTRAINT FK_EQUIPES_VOO_ID FOREIGN KEY (EQUIPES_VOO_ID) REFERENCES VOOS (VOO_ID)
);


ALTER TABLE AEROPORTOS
ADD COLUMN AEROP_WEBSITE VARCHAR(100);

ALTER TABLE AEROPORTOS
DROP COLUMN AEROP_CEP;

ALTER TABLE AEROPORTOS
MODIFY COLUMN AEROP_LATITUDE DECIMAL(10,8) NOT NULL,
MODIFY COLUMN AEROP_LONGITUDE DECIMAL(11,8) NOT NULL;

ALTER TABLE AEROPORTOS
CHANGE COLUMN AEROP_NOME NOME_AEROPORTO VARCHAR(30) NOT NULL;


ALTER TABLE AERONAVES
ADD COLUMN AERON_MATRICULA VARCHAR(20);

ALTER TABLE AERONAVES
DROP COLUMN AERON_ANOFABR;

ALTER TABLE AERONAVES
MODIFY COLUMN AERON_AUTONOMIA INT,
MODIFY COLUMN AERON_CAPACIDADE INT;

ALTER TABLE AERONAVES
CHANGE COLUMN AERON_PREFIXO PREFIXO_AERONAVE INT PRIMARY KEY;


ALTER TABLE PASSAGEIROS
ADD COLUMN PASS_DATANASCIMENTO DATE;

ALTER TABLE PASSAGEIROS
DROP COLUMN PASS_TELEFONE;

ALTER TABLE PASSAGEIROS
MODIFY COLUMN PASS_CPF VARCHAR(11) PRIMARY KEY;

ALTER TABLE PASSAGEIROS
CHANGE COLUMN PASS_NOME NOME_PASSAGEIRO VARCHAR(30) NOT NULL;


ALTER TABLE RESERVAS
ADD COLUMN RESERVA_DATA DATE NOT NULL;

ALTER TABLE RESERVAS
DROP COLUMN RESERVA_VOO_ID;

ALTER TABLE RESERVAS
MODIFY COLUMN RESERVA_COD VARCHAR(10) PRIMARY KEY;

ALTER TABLE RESERVAS
CHANGE COLUMN RESERVA_PASS_CPF CPF_PASSAGEIRO_RESERVA INT NOT NULL;


ALTER TABLE VOOS
ADD COLUMN VOO_STATUS VARCHAR(20);

ALTER TABLE VOOS
DROP COLUMN VOO_HORA;

ALTER TABLE VOOS
MODIFY COLUMN VOO_DATA DATETIME NOT NULL;

ALTER TABLE VOOS
CHANGE COLUMN VOO_ID CODIGO_VOO INT PRIMARY KEY;


ALTER TABLE FUNCIONARIOS
ADD COLUMN FUNCK_SALARIO DECIMAL(10,2);

ALTER TABLE FUNCIONARIOS
DROP COLUMN FUNCK_CEP;

ALTER TABLE FUNCIONARIOS
MODIFY COLUMN FUNCK_CPF VARCHAR(11) NOT NULL;

ALTER TABLE FUNCIONARIOS
CHANGE COLUMN FUNCK_NOME NOME_FUNCIONARIO VARCHAR(45) NOT NULL;


DROP DATABASE EMPRESA_PASSAGENS_AEREAS;